version: '2'

services:
  backend:
    build: ./backend
    volumes:
      - ./:/app
    ports:
      - '3333:3333'
    depends_on:
      - mongo
    networks:
      - upsale_x  

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_db:/data/db
    networks:
      - upsale_x
      
  frontend:
    build: ./portal
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    networks:
      - upsale_x

networks:
  upsale_x:
