version: '2'

services:
  backend:
    build: ./backend
    volumes:
      - ./:/app
    ports:
      - '3333:3333'
    depends_on:
      - mongo
    networks:
      - upsale_x  

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_db:/data/db
    networks:
      - upsale_x
      
  portal:
    build:
      context: ./portal/
    command: npm start
    volumes:
      - ./portal/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - '3000:3000'
    networks:
      - upsale_x

networks:
  upsale_x:
